[profile.default]
src = "contracts/src"
test = "contracts/test"
script = "contracts/script"
out = "contracts/out"
libs = ["contracts/lib", "node_modules"]
solc_version = "0.8.19"
optimizer = true
optimizer_runs = 1000
remappings = [
  "@somnia-chain/reactivity-contracts/=contracts/lib/somnia-reactivity-contracts/"
]

[fmt]
line_length = 100
tab_width = 4
bracket_spacing = true
